(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



gamma[0]={{0,0,1,0},{0,0,0,1},{1,0,0,0},{0,1,0,0}};
gamma[1]={{0,0,0,1},{0,0,1,0},{0,-1,0,0},{-1,0,0,0}};
gamma[2]={{0,0,0,-I},{0,0,I,0},{0,I,0,0},{-I,0,0,0}};
gamma[3]={{0,0,1,0},{0,0,0,-1},{-1,0,0,0},{0,+1,0,0}};
gamma[5] = I gamma[0]. gamma[1].gamma[2].gamma[3];
sigma[u_,v_]:=I/2 (gamma[u].gamma[v]-gamma[v].gamma[u])



